# Site settings
name: Mitta Pei
description: "爱孩子 爱生活"
url: "www.mittapei.cn"


# Delete the lines you don't need
# about 5 elements are recomended
blog_url: "/blog"
weibo_username: http://weibo.com/mittapei
instagram_username:  https://www.instagram.com/mittapei
linkedin_username: https://cn.linkedin.com/in/侠敏-裴-214aa5137
email: mitta.pei@firstleap.cn


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "imgs/avatar.png"


front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
